#!/bin/bash

# Second step: analyzes WHAT CHANGED between dependency versions using the
# dependency_status.json generated by check-dependencies.sh.
#
# Usage:
#   ./check-changelog.sh [path/to/dependency_status.json] [options for changelog-diff.py]
#
# Examples:
#   ./check-changelog.sh                                     # uses ./dependency_status.json
#   ./check-changelog.sh ./dependency_status.json --md changelog.md
#   ./check-changelog.sh --summarize --api-key sk-ant-...    # LLM enrichment with API key
#   ./check-changelog.sh --github-token ghp_...              # pass GitHub token as argument
#   WITH_CRAWL4AI=1 ./check-changelog.sh                     # install crawl4AI (fallback)
#   ./check-changelog.sh --summarize --provider bedrock  # AWS Bedrock (auto-installs boto3)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${SCRIPT_DIR}/venv-changelog"
PYTHON_SCRIPT="${SCRIPT_DIR}/changelog-diff.py"

echo "🚀 Starting dependency changelog analyzer"

# Create virtual environment if it doesn't exist
if [ ! -d "${VENV_DIR}" ]; then
  echo "🔨 Creating virtual environment at ${VENV_DIR}..."
  python3 -m venv "${VENV_DIR}" || { echo "❌ Failed to create virtual environment"; exit 1; }
fi

# Locate the venv binaries (Windows/Git Bash uses Scripts/ instead of bin/)
if [ -x "${VENV_DIR}/Scripts/python.exe" ]; then
  VENV_PYTHON="${VENV_DIR}/Scripts/python.exe"
elif [ -x "${VENV_DIR}/bin/python" ]; then
  VENV_PYTHON="${VENV_DIR}/bin/python"
else
  echo "❌ Error: Python interpreter not found in ${VENV_DIR}"
  exit 1
fi

# Install base dependencies (requests, anthropic, pydantic).
echo "📦 Installing dependencies..."
REQUIREMENTS="${SCRIPT_DIR}/requirements.txt"
if [ -f "${REQUIREMENTS}" ]; then
  PIP_ARGS=(-r "${REQUIREMENTS}")
else
  PIP_ARGS=(requests)
fi
if ! "${VENV_PYTHON}" -m pip install --quiet "${PIP_ARGS[@]}"; then
  echo "❌ Failed to install dependencies"
  exit 1
fi

# crawl4AI is optional: only installed if you set WITH_CRAWL4AI=1.
# It pulls in Playwright and a headless browser, so opt-in avoids that weight in CI.
if [ "${WITH_CRAWL4AI:-0}" = "1" ]; then
  echo "📦 Installing crawl4AI (requested via WITH_CRAWL4AI=1)..."
  CRAWL_REQ="${SCRIPT_DIR}/requirements-crawl4ai.txt"
  if [ -f "${CRAWL_REQ}" ]; then
    "${VENV_PYTHON}" -m pip install --quiet -r "${CRAWL_REQ}" || \
      echo "⚠️  Could not install crawl4AI; the script will use the plain HTML fallback."
  else
    "${VENV_PYTHON}" -m pip install --quiet "crawl4ai>=0.4.0" || \
      echo "⚠️  Could not install crawl4AI; the script will use the plain HTML fallback."
  fi

  # crawl4AI needs to download the Playwright browser once.
  if [ "${SKIP_CRAWL4AI:-0}" != "1" ]; then
    echo "🌐 Preparing crawl4AI browser (Playwright)..."
    "${VENV_PYTHON}" -m playwright install chromium >/dev/null 2>&1 || \
      echo "⚠️  Could not download Playwright browser; AndroidX will use the plain HTML fallback."
  fi
fi

# Bedrock: auto-install boto3 when --provider bedrock is in the arguments.
NEEDS_BEDROCK=0
for arg in "$@"; do
  if [ "$arg" = "bedrock" ] || [ "${WITH_BEDROCK:-0}" = "1" ]; then
    NEEDS_BEDROCK=1
    break
  fi
done
if [ "${NEEDS_BEDROCK}" = "1" ]; then
  echo "📦 Installing Bedrock support (boto3 + AWS SDK)..."
  "${VENV_PYTHON}" -m pip install --quiet "anthropic[bedrock]>=0.40.0" || \
    echo "⚠️  Could not install Bedrock dependencies; use --provider anthropic instead."
fi

echo "🔎 Analyzing changes between versions..."
"${VENV_PYTHON}" "${PYTHON_SCRIPT}" "$@"
RESULT=$?

if [ ${RESULT} -ne 0 ]; then
  echo "❌ Analysis failed"
  exit ${RESULT}
fi

echo "✨ Done"
