"""CLI entry point: argparse, orchestration and main()."""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import sys
from datetime import datetime
from typing import Any

import changelog_diff
from . import log
from .adapters import SourceRouter
from .cache import Cache
from .http import Fetcher
from .intel import build_intel_document, compare_intel
from .llm import make_client, summarize_with_llm
from .models import Dependency, load_dependencies
from .render import render_markdown, render_intel_markdown


def process_dependency(
    dep: Dependency, fetcher: Fetcher, router: SourceRouter,
    cache: Cache, include_prereleases: bool,
    summarize: bool, model: str, client: Any = None,
) -> dict[str, Any]:
    cached = cache.get(dep)
    if cached is not None:
        log(f"   💾 {dep.coordinate} (cache)")
        result = cached
    else:
        log(f"   🔎 {dep.coordinate}  {dep.version_used} → {dep.latest_stable}")
        resolved = router.resolve(fetcher, dep, include_prereleases)
        result = {
            "coordinate": dep.coordinate,
            "type": dep.dep_type,
            "status_code": dep.status_code,
            "from": dep.version_used,
            "to": dep.latest_stable,
            "source": resolved["source"],
            "source_url": resolved["source_url"],
            "versions": resolved["notes"],
        }
        cache.put(dep, result)

    if (summarize and client is not None and result.get("versions")
            and "summary" not in result):
        combined = "\n\n".join(
            f"# {n['version']} ({n.get('date') or 's/f'})\n{n['notes']}"
            for n in result["versions"]
        )
        summary = summarize_with_llm(
            dep.coordinate, dep.version_used, dep.latest_stable,
            combined, model, client,
        )
        if summary:
            result["summary"] = summary
            cache.put(dep, result)
    return result


def main() -> int:
    changelog_diff._QUIET = False
    parser = argparse.ArgumentParser(
        description="Analyze what changed between dependency versions "
                    "using the owner's documentation.",
    )
    parser.add_argument(
        "status_json", nargs="?", default="dependency_status.json",
        help="Path to the JSON generated by check-dependencies.sh.",
    )
    parser.add_argument(
        "-o", "--output", default="changelog_diff.json",
        help="Output JSON file path.",
    )
    parser.add_argument(
        "--md", metavar="PATH",
        help="Also write a human-readable Markdown file at this path.",
    )
    parser.add_argument(
        "--format", choices=("raw", "intel"), default="raw",
        help="raw = raw notes per version (default). "
             "intel = change-intel-1 schema.",
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Analyze all dependencies, not just outdated ones.",
    )
    parser.add_argument(
        "--include-prereleases", action="store_true",
        help="Include intermediate alphas/betas/rc in the range.",
    )
    parser.add_argument(
        "--summarize", action="store_true",
        help="Enrich with LLM (requires --api-key or --provider bedrock).",
    )
    parser.add_argument(
        "--summarize-scope", choices=("major", "all"), default="major",
        help="Which deps the LLM applies to in --format intel.",
    )
    parser.add_argument(
        "--summarize-only", default="",
        help="Comma-separated coordinates to enrich with LLM.",
    )
    parser.add_argument(
        "--compare", action="store_true",
        help="Run heuristic vs LLM (intel), report the delta.",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("ANTHROPIC_API_KEY"),
        help="Anthropic API key (or ANTHROPIC_API_KEY env var).",
    )
    parser.add_argument(
        "--provider",
        choices=("anthropic", "bedrock"),
        default=os.environ.get("LLM_PROVIDER", "anthropic"),
        help="LLM provider: 'anthropic' (direct API) or 'bedrock' "
             "(AWS Bedrock). Env var: LLM_PROVIDER.",
    )
    parser.add_argument(
        "--aws-region",
        default=os.environ.get("AWS_REGION"),
        help="AWS region for Bedrock (or AWS_REGION env var).",
    )
    parser.add_argument(
        "--aws-profile",
        default=os.environ.get("AWS_PROFILE"),
        help="AWS profile for Bedrock credentials (or AWS_PROFILE env var).",
    )
    parser.add_argument(
        "--model",
        default=os.environ.get("ANTHROPIC_MODEL", "claude-haiku-4-5-20251001"),
        help="Model for summaries (or ANTHROPIC_MODEL env var). "
             "Default: claude-haiku-4-5-20251001. "
             "Auto-mapped to Bedrock format when --provider bedrock.",
    )
    parser.add_argument(
        "--cache-dir", default=".changelog-cache",
        help="Per-version cache directory.",
    )
    parser.add_argument(
        "--github-token", default=os.environ.get("GITHUB_TOKEN"),
        help="GitHub token to increase the rate limit.",
    )
    parser.add_argument(
        "--androidx-lang",
        default=os.environ.get("ANDROIDX_LANG", "es-419"),
        help="Language for AndroidX pages via ?hl= parameter.",
    )
    parser.add_argument(
        "--no-crawl4ai", action="store_true",
        help="Don't use crawl4AI in fallback (avoids Playwright in CI).",
    )
    parser.add_argument(
        "--max-releases", type=int, default=300,
        help="Maximum GitHub releases to scan per dependency.",
    )
    parser.add_argument(
        "-j", "--jobs", type=int, default=6,
        help="Parallel dependency workers.",
    )
    parser.add_argument(
        "--timeout", type=int, default=20,
        help="Timeout per HTTP request (seconds).",
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true",
        help="Suppress progress output.",
    )
    args = parser.parse_args()

    BEDROCK_MODELS = {
        "claude-haiku-4-5-20251001": "us.anthropic.claude-haiku-4-5-20251001-v1:0",
        "claude-sonnet-5": "us.anthropic.claude-sonnet-5-20250514-v1:0",
        "claude-opus-5-5": "us.anthropic.claude-opus-5-5-20250918-v1:0",
    }
    if args.provider == "bedrock" and args.model in BEDROCK_MODELS:
        args.model = BEDROCK_MODELS[args.model]

    changelog_diff._QUIET = args.quiet

    if not os.path.exists(args.status_json):
        print(
            f"❌ {args.status_json} not found. "
            f"Run check-dependencies.sh first.",
            file=sys.stderr,
        )
        return 1

    deps = load_dependencies(args.status_json, include_all=args.all)
    if not deps:
        log("✅ No dependencies to analyze. Use --all to force.")
        if args.format == "intel":
            empty_doc = {
                "schema": "deps-changelog-diff/change-intel-1",
                "meta": {
                    "generated_at": datetime.now().isoformat(
                        timespec="seconds"
                    ),
                    "enrichment": "none",
                    "totals": {
                        "analyzed": 0, "with_changes": 0, "no_source": 0,
                    },
                },
                "project_gates": [],
                "dependencies": {},
            }
            with open(args.output, "w", encoding="utf-8") as handle:
                json.dump(empty_doc, handle, ensure_ascii=False, indent=2)
            if args.md:
                with open(args.md, "w", encoding="utf-8") as handle:
                    handle.write(render_intel_markdown(empty_doc))
        else:
            with open(args.output, "w", encoding="utf-8") as handle:
                json.dump({}, handle)
            if args.md:
                with open(args.md, "w", encoding="utf-8") as handle:
                    handle.write(render_markdown([]))
        return 0

    api_key = args.api_key
    client = None
    if args.summarize or args.compare:
        if args.provider == "anthropic" and not api_key:
            log("   ⚠️  --summarize requested but no API key provided. "
                "Use --api-key or ANTHROPIC_API_KEY.")
        else:
            client = make_client(
                provider=args.provider,
                api_key=api_key,
                aws_region=args.aws_region,
                aws_profile=args.aws_profile,
            )

    cache_dir = (
        None if args.cache_dir.lower() in ("", "none") else args.cache_dir
    )
    opts_key = (
        f"pre={args.include_prereleases};"
        f"lang={args.androidx_lang};"
        f"max={args.max_releases}"
    )
    cache = Cache(cache_dir, opts_key=opts_key)
    router = SourceRouter(
        max_releases=args.max_releases, androidx_lang=args.androidx_lang,
    )
    fetcher = Fetcher(
        timeout=args.timeout, github_token=args.github_token,
        use_crawl4ai=not args.no_crawl4ai,
    )

    deps_by_coord = {d.coordinate: d for d in deps}
    only = [c.strip() for c in args.summarize_only.split(",") if c.strip()]
    summary_in_fetch = (
        args.format == "raw" and args.summarize and not args.compare
        and client is not None
    )

    log(f"🚀 Analyzing {len(deps)} dependencies...")
    results: list[dict[str, Any]] = []
    failed = 0
    with concurrent.futures.ThreadPoolExecutor(
        max_workers=max(1, args.jobs)
    ) as pool:
        futures = {
            pool.submit(
                process_dependency, dep, fetcher, router, cache,
                args.include_prereleases, summary_in_fetch,
                args.model, client,
            ): dep
            for dep in deps
        }
        for future in concurrent.futures.as_completed(futures):
            dep = futures[future]
            try:
                results.append(future.result())
            except Exception as exc:
                failed += 1
                log(f"   ❌ {dep.coordinate}: {type(exc).__name__}: {exc}")
    results.sort(key=lambda r: r["coordinate"])
    if failed:
        log(f"   ⚠️  {failed} dependency(ies) failed during analysis.")

    def _write(path: str, obj: Any) -> None:
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(obj, handle, ensure_ascii=False, indent=2)
        log(f"💾 Written {path}")

    if args.compare:
        base = (
            args.output[:-5]
            if args.output.endswith(".json") else args.output
        )
        heur = build_intel_document(
            deps_by_coord, results, summarize=False,
            scope=args.summarize_scope, only=only,
            model=args.model, client=client,
        )
        _write(f"{base}.heuristic.json", heur)
        if client is None:
            log("⚠️  --compare without LLM credentials: heuristic only.")
            return 0
        llm = build_intel_document(
            deps_by_coord, results, summarize=True,
            scope=args.summarize_scope, only=only,
            model=args.model, client=client,
        )
        _write(f"{base}.llm.json", llm)
        delta = compare_intel(heur, llm)
        print("\n===== Heuristic vs LLM comparison =====")
        print(f"  deps enriched by LLM      : {delta['deps_enriched']}")
        print(f"  replacements (old->new)   : +{delta['replacements_added']}")
        print(f"  kinds refined             : +{delta['kinds_refined']}")
        print(f"  seeds cleaned (noise)     : -{delta['seeds_cleaned']}")
        for h in delta["highlights"]:
            print(f"    • {h}")
        _write(f"{base}.compare.json", delta)
        return 0

    if args.format == "intel":
        doc = build_intel_document(
            deps_by_coord, results, summarize=args.summarize,
            scope=args.summarize_scope, only=only,
            model=args.model, client=client,
        )
        _write(args.output, doc)
        if args.md:
            with open(args.md, "w", encoding="utf-8") as handle:
                handle.write(render_intel_markdown(doc))
            log(f"📝 Written {args.md}")
        tt = doc["meta"]["totals"]
        log(
            f"✨ Done (intel/{doc['meta']['enrichment']}): "
            f"{tt['with_changes']}/{tt['analyzed']} with changes, "
            f"{tt['no_source']} without source."
        )
        return 0

    output = {r["coordinate"]: r for r in results}
    _write(args.output, output)
    if args.md:
        with open(args.md, "w", encoding="utf-8") as handle:
            handle.write(render_markdown(results))
        log(f"📝 Written {args.md}")
    found = sum(1 for r in results if r.get("versions"))
    log(f"✨ Done: {found}/{len(results)} with release notes found.")
    return 0
